version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200"
    depends_on:
      - backend
      - localstack

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8081:8081"
    environment:
      - SERVICES=dynamodb,apigateway,lambda,sns
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
